name: speech_craft
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_adaptive_scaffold: ^0.1.10+1
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.2
  get_it: ^7.6.7
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  youtube_player_iframe: ^5.1.2
  jumping_dot: ^0.0.6
  permission_handler: ^11.3.1
  record: ^5.0.4
  audioplayers: ^6.0.0
  media_kit_libs_windows_video: any
  syncfusion_flutter_charts: ^24.1.44+1
  intl: ^0.18.0

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
