name: speech_craft
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_adaptive_scaffold: ^0.1.10+1
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.2
  get_it: ^7.6.7
  video_player: ^2.8.2

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mockito: ^5.4.4
  build_runner: ^2.4.9
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
