// Mocks generated by Mockito 5.4.4 from annotations
// in speech_craft/test/domain/use_cases/search_query_params_use_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:speech_craft/domain/entities/language_entity.dart' as _i3;
import 'package:speech_craft/domain/entities/region_code_entity.dart' as _i4;
import 'package:speech_craft/domain/repositories/search_query_params_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SearchQueryParamsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchQueryParamsRepository extends _i1.Mock
    implements _i2.SearchQueryParamsRepository {
  @override
  List<_i3.LanguageEntity> getLanguagesFromDatasource() => (super.noSuchMethod(
        Invocation.method(
          #getLanguagesFromDatasource,
          [],
        ),
        returnValue: <_i3.LanguageEntity>[],
        returnValueForMissingStub: <_i3.LanguageEntity>[],
      ) as List<_i3.LanguageEntity>);

  @override
  List<_i4.RegionCodeEntity> getRegionCodesFromDatasource() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegionCodesFromDatasource,
          [],
        ),
        returnValue: <_i4.RegionCodeEntity>[],
        returnValueForMissingStub: <_i4.RegionCodeEntity>[],
      ) as List<_i4.RegionCodeEntity>);
}
