// Mocks generated by Mockito 5.4.4 from annotations
// in speech_craft/test/data/repositories/pauses_repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:speech_craft/data/data_sources/video_data/pauses_remote_source.dart'
    as _i2;
import 'package:speech_craft/data/models/pauses_response/timestamps.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PausesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPausesRemoteDataSource extends _i1.Mock
    implements _i2.PausesRemoteDataSource {
  @override
  _i3.Future<List<_i4.Timestamp>> getPauses({required String? videoId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPauses,
          [],
          {#videoId: videoId},
        ),
        returnValue: _i3.Future<List<_i4.Timestamp>>.value(<_i4.Timestamp>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Timestamp>>.value(<_i4.Timestamp>[]),
      ) as _i3.Future<List<_i4.Timestamp>>);
}
